---

  - name: Create directory for deployment files
    file:
      path: /setup
      state: directory
      mode: '0755'

  - name: Copy SAP Hana Deployment files
    copy:
      src: "{{ hana_deployment['source'] }}/{{ item.src }}"
      dest: "/setup"
      owner: root
      group: root
      mode: '0755'
    with_items:
      - { src: "{{ hana_deployment['server'] }}" }
      - { src: "{{ hana_deployment['client'] }}" }
      - { src: "{{ hana_deployment['sapcar'] }}" }
      - { src: "{{ hana_deployment['hostagent'] }}" }
#      - { src: "{{ hana_deployment['spp'] }}" }

  - name: Ansible SAP Hana Database Directory exists.
    stat:
      path: /setup/SAP_HANA_DATABASE
    register: hana_db_directory

  - name: Ansible SAP Hana Client Directory exists.
    stat:
      path: /setup/SAP_HANA_CLIENT
    register: hana_client_directory

  - name: Extract SAP Hana Database Deployment Files
    command:
      cmd: "./{{ hana_deployment['sapcar'] }} -manifest SIGNATURE.SMF -xvf {{ hana_deployment['server'] }}"
      chdir: "/setup"
    when: hana_db_directory.stat.isdir is not defined

  - name: Extract SAP Hana Client Deployment Files
    command:
      cmd: "./{{ hana_deployment['sapcar'] }} -xvf {{ hana_deployment['client'] }}"
      chdir: "/setup"
    when: hana_client_directory.stat.isdir is not defined

  - name: SIGNATURE.SMF file exists.
    stat:
      path: /setup/SIGNATURE.SMF
    register: hana_signature_file

  - name: Copy The SIGNATURE.SMF file to /setup/SAP_HANA_DATABASE
    command: "cp /setup/SIGNATURE.SMF /setup/SAP_HANA_DATABASE"
    when: hana_signature_file.stat.exists is defined
