---
  - name: Check SAP Haost Agent Installed Status
    stat:
      path: "/usr/sap/hostctrl/exe/saphostctrl"
    register: sap_host_agent

  - name: Ensure SAP Host Agent is installed or updated from RPM
    package:
      name: /setup/"{{ hana_deployment['hostagent'] }}"
      state: present
    when: sap_host_agent.stat.isdir is not defined
    notify: start_saphostagent

  - name: Work out id db is up
    shell: "/usr/sap/hostctrl/exe/saphostctrl -nr 99 -function GetDatabaseStatus -dbname SYSTEMDB@{{ sid }} -dbtype hdb -host {{ ansible_hostname }} -format script | awk '/Database Status: /{print $3}'"
    register: host_agent

  - debug:
     msg: Database {{ sid }} is {{ host_agent.stdout }} properly
     #verbosity: 2

  - fail:
     msg: Hana Databse is not running properly !!!
    when: host_agent.stdout != "Running"

  - name: GET A LIST of databases
    shell: "/usr/sap/hostctrl/exe/saphostctrl -nr 99 -function Listdatabases"
    register: list_datatabase

  - debug:
      var: list_datatabase.stdout_lines
