---

 - read_csv:
     path: /root/ansible/host-vms-csv/vms-sdflex.csv
     key: hostname
   register: vms


 - name: Create Ansible Hosts File
   lineinfile:
     dest: /root/ansible/hosts
     insertafter: '[hana]'
     line: "{{ item.value.hostname }} ansible_host={{ item.value.data_ip }}"
   loop: "{{ vms.dict|dict2items }}"

