---
- hosts: localhost
  gather_facts: no

  roles:
    - { role: host-variable-vmware } # role::host-variable-vmware


- hosts: hana
  serial: 4
  remote_user: root
  gather_facts: no

  vars:
          installation_media: SLE-15-SP5-SAP-x86_64-DVD.iso
          iso_datastore: TEMP-DS02
          datastore_iso_directory: ISO

          # HANA Operating System Firewall / ture Or false
          firewall: false

          # Two Factor Authentication
          two_way_auth: true
          pam_module: google-authenticator-libpam-1.09-15.2.x86_64.rpm

          # Vmware Virtual Center Credentails
          vcenter_hostname: xxxxx
          vcenter_username: administrator@vsphere.local
          vcenter_password: xxxxxx

          # Sap Servers Hostname / IP Informations
          fqdn: hpetrlab.local

          # Mail Relay Host / Admin Mail Address
          # relayhost: smtp.office365.com If Customer using relay mail to Office 365
          relayhost: smtp.office365.com
          recipientmail: emre.baykal@hpetrlab.local
          sendermail: sap@hpetrlab.local
          # sendermail_password: sender mail password If Customer using relay mail to Office 365, oherwise keep blank
          sendermail_password: 
          mail_domain: hpetrlab.local

          # Remote Sys Log Server // Keep Blank if not rsyslog server desired
          rsys_log_srv: xx.xx.xx.xx
          rsys_log_srv_port: 514
          # Transport Protocal May use tcp or udp
          rsys_protocol: udp

          # Time Sync Parameters
          ntp_servers:
            - xx.xx.xx.xx
            - xx.xx.xx.xx

          # Monitoring Thresholds
          monitoring: true
          # CPU Usage % Threshold
          cpu_threshold: 85
          # Memory Usage % Threshold
          mem_threshold: 85
          # Disk Usage % Threshold
          disk_threshold: 80

          # HPE Oneview Config Parameters
          oneview_ip: XXX.XXX.XXX.XXX
          oneview_username: administrator
          oneview_password: xxxxxxxxxx
          email_sender: server@hpelab.local

          # Hana StoreOnce Catalyst Plug In Config
          catalyst_plugin: HPE_StoreOnce_Catalyst_Plug_in_2.2.0_for_SAP_HANA_Linux_EH991-91007.tar.gz
          storeonce_ip: xxx.xxx.xxx.xxx
          storeonce_username: Admin
          storeonce_password: XXXXXXXXX
          catalyst_client_password: XXXXXXXX
          storeonce_config: true

          # Hana Installation files
          hana_deployment:
              server: IMDB_SERVER20_076_0-80002031.SAR
              client: IMDB_CLIENT20_019_21-80002082.SAR
              sapcar: SAPCAR_1324-80000935.EXE
              hostagent: saphostagentrpm_62-80004822.rpm
              spp: P26228_001_spp-2019.12.0-SPP2019120.2019_1209.4.iso
              source: /root/media
              destination: /setup


  roles:
          - { role: vmware-guest-deployment }         # role::vmware-guest-deployment
          - { role: sap-hana-preconfigure-vmware }    # role::sap-hana-preconfigure-vmware
          - { role: sap-hana-security-hardening }     # role::sap-hana-security-hardening
          - { role: sap-hana-deploy }                 # role::sap-hana-deploy
          - { role: sap-hana-replication }            # role::sap-hana-replication
          - { role: sap-hana-storeonce-backup }       # role::sap-hana-storeonce-backup
          - { role: sap-hana-mfa }                    # role::sap-hana-mfa
          - { role: oneview-config }                  # role::oneview-config
