#!/bin/bash

# SAP HANA Full System Report Generator
# Version: 2.0
# Description: Comprehensive system and SAP HANA analysis tool

set -euo pipefail  # Exit on error, undefined variables, and pipe failures

# Configuration
readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly HOSTNAME="$(hostname -s)"
readonly TIMESTAMP="$(date +%F_%H-%M-%S)"
readonly OUTDIR="${REPORT_DIR:-/root}"
readonly OUTFILE="${OUTDIR}/hana_full_report_${HOSTNAME}_${TIMESTAMP}.txt"
readonly LOG_LEVEL="${LOG_LEVEL:-INFO}"

# Colors for output
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly BLUE='\033[0;34m'
readonly NC='\033[0m' # No Color

# Initialize report
init_report() {
    # Create output directory if it doesn't exist
    mkdir -p "$OUTDIR"
    
    # Initialize report file
    cat > "$OUTFILE" << EOF
================================================================================
                    FULL SAP HANA SYSTEM REPORT
================================================================================
Host: $(hostname -f)
Generated on: $(date)
Generated by: $(whoami)
Script Version: 2.0
Report File: $OUTFILE
================================================================================

EOF
}

# Logging functions
log_info() {
    [[ "$LOG_LEVEL" =~ ^(DEBUG|INFO)$ ]] && echo -e "${GREEN}[INFO]${NC} $*" >&2
}

log_warn() {
    [[ "$LOG_LEVEL" =~ ^(DEBUG|INFO|WARN)$ ]] && echo -e "${YELLOW}[WARN]${NC} $*" >&2
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $*" >&2
}

log_debug() {
    [[ "$LOG_LEVEL" == "DEBUG" ]] && echo -e "${BLUE}[DEBUG]${NC} $*" >&2
}

# Progress indicator
show_progress() {
    echo -e "${BLUE}[PROGRESS]${NC} $*" >&2
}

# Section header function with improved formatting
section() {
    local title="$1"
    local timestamp="$(date '+%Y-%m-%d %H:%M:%S')"
    
    cat >> "$OUTFILE" << EOF

################################################################################
# $title
# Collected at: $timestamp
################################################################################

EOF
    show_progress "Collecting: $title"
}

# Safe command execution with error handling
safe_exec() {
    local cmd="$*"
    local result
    
    log_debug "Executing: $cmd"
    
    if result=$(eval "$cmd" 2>&1); then
        echo "$result" >> "$OUTFILE"
        return 0
    else
        echo "ERROR: Command failed - $cmd" >> "$OUTFILE"
        echo "Error output: $result" >> "$OUTFILE"
        log_warn "Command failed: $cmd"
        return 1
    fi
}

# Check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# System Information Collection Functions
collect_system_info() {
    section "System Information Summary"
    {
        echo "Hostname (short): $(hostname -s)"
        echo "Hostname (FQDN): $(hostname -f 2>/dev/null || hostname -s)"
        echo "Operating System: $(get_os_info)"
        echo "Kernel Version: $(uname -r)"
        echo "Architecture: $(uname -m)"
        echo "System Uptime: $(uptime -p 2>/dev/null || uptime)"
        echo "Current User: $(whoami)"
        echo "System Load: $(uptime | awk -F'load average:' '{print $2}')"
    } >> "$OUTFILE"

    section "Detailed OS Information"
    if [[ -f /etc/os-release ]]; then
        safe_exec "cat /etc/os-release"
    elif [[ -f /etc/redhat-release ]]; then
        safe_exec "cat /etc/redhat-release"
    elif [[ -f /etc/SuSE-release ]]; then
        safe_exec "cat /etc/SuSE-release"
    else
        echo "OS release information not found" >> "$OUTFILE"
    fi

    section "Kernel Information"
    safe_exec "uname -a"
    safe_exec "cat /proc/version"

    section "System Date and Time"
    safe_exec "date"
    if command_exists timedatectl; then
        safe_exec "timedatectl"
    fi
    
    section "Timezone Configuration"
    safe_exec "cat /etc/timezone" || safe_exec "ls -la /etc/localtime"
}

# Helper function to get OS info
get_os_info() {
    if [[ -f /etc/os-release ]]; then
        . /etc/os-release
        echo "$PRETTY_NAME"
    elif [[ -f /etc/redhat-release ]]; then
        cat /etc/redhat-release
    elif [[ -f /etc/SuSE-release ]]; then
        head -n1 /etc/SuSE-release
    else
        echo "Unknown Linux Distribution"
    fi
}

collect_hardware_info() {
    section "Hardware Summary"
    {
        echo "CPU Model: $(grep 'model name' /proc/cpuinfo | head -1 | cut -d: -f2 | sed 's/^ *//')"
        echo "CPU Cores: $(nproc)"
        echo "Total Memory: $(free -h | awk '/^Mem:/ {print $2}')"
        echo "Available Memory: $(free -h | awk '/^Mem:/ {print $7}')"
    } >> "$OUTFILE"

    section "Detailed CPU Information"
    if command_exists lscpu; then
        safe_exec "lscpu"
    else
        safe_exec "cat /proc/cpuinfo"
    fi

    section "Memory Information"
    safe_exec "free -h"
    echo "" >> "$OUTFILE"
    safe_exec "cat /proc/meminfo | head -20"

    section "NUMA Configuration"
    if command_exists numactl; then
        safe_exec "numactl --hardware"
        safe_exec "numactl --show"
    else
        echo "numactl command not available" >> "$OUTFILE"
    fi

    section "HugePages Configuration"
    safe_exec "grep -E '^(HugePages|Hugepagesize)' /proc/meminfo"
    
    section "Transparent HugePages Status"
    if [[ -f /sys/kernel/mm/transparent_hugepage/enabled ]]; then
        echo "THP Enabled: $(cat /sys/kernel/mm/transparent_hugepage/enabled)" >> "$OUTFILE"
    fi
    if [[ -f /sys/kernel/mm/transparent_hugepage/defrag ]]; then
        echo "THP Defrag: $(cat /sys/kernel/mm/transparent_hugepage/defrag)" >> "$OUTFILE"
    fi

    section "I/O Scheduler Configuration"
    for device in /sys/block/*/queue/scheduler; do
        if [[ -f "$device" ]]; then
            block_device=$(echo "$device" | cut -d/ -f4)
            echo "Device $block_device: $(cat "$device")" >> "$OUTFILE"
        fi
    done

    section "Hardware Details"
    if command_exists lshw; then
        safe_exec "lshw -short"
    fi
    
    if command_exists dmidecode; then
        safe_exec "dmidecode -t system | head -20"
    fi
}

collect_storage_info() {
    section "Storage Overview"
    safe_exec "df -h"
    echo "" >> "$OUTFILE"
    safe_exec "lsblk -f"

    section "Filesystem Table (fstab)"
    safe_exec "cat /etc/fstab"

    section "Mount Points"
    safe_exec "mount | column -t"

    section "LVM Configuration"
    if command_exists pvs; then
        safe_exec "pvs -v"
        safe_exec "vgs -v"
        safe_exec "lvs -v"
    else
        echo "LVM tools not available" >> "$OUTFILE"
    fi

    section "Storage Device Information"
    safe_exec "lsblk -D"  # Show discard capabilities
    
    section "Disk I/O Statistics"
    if command_exists iostat; then
        safe_exec "iostat -x 1 3"
    fi

    section "SAP HANA Relevant Storage"
    {
        echo "=== HANA Data and Log Directories ==="
        find /hana -maxdepth 3 -type d 2>/dev/null | head -20 || echo "No /hana directory found"
        echo ""
        echo "=== SAP Installation Directory ==="
        ls -la /usr/sap/ 2>/dev/null || echo "No /usr/sap directory found"
    } >> "$OUTFILE"
}

collect_network_info() {
    section "Network Interface Summary"
    {
        echo "=== Active Network Interfaces ==="
        ip -o link show | awk '{print $2, $3, $9}'
        echo ""
        echo "=== IP Address Summary ==="
        ip -o addr show | grep -E "inet[^6]" | awk '{print $2, $4}'
    } >> "$OUTFILE"

    section "Network Interface Details"
    if command_exists ip; then
        safe_exec "ip addr show"
    else
        safe_exec "ifconfig -a"
    fi

    section "Routing Table"
    if command_exists ip; then
        safe_exec "ip route show"
        safe_exec "ip -6 route show"
    else
        safe_exec "route -n"
    fi

    section "Network Bonding Configuration"
    local bond_found=false
    for bond_file in /proc/net/bonding/bond*; do
        if [[ -f "$bond_file" ]]; then
            bond_found=true
            echo "=== Bond Interface: $(basename "$bond_file") ===" >> "$OUTFILE"
            safe_exec "cat $bond_file"
        fi
    done
    [[ "$bond_found" == false ]] && echo "No bonded interfaces found" >> "$OUTFILE"

    section "DNS Configuration"
    safe_exec "cat /etc/resolv.conf"
    if [[ -f /etc/hosts ]]; then
        echo "" >> "$OUTFILE"
        echo "=== Hosts File (relevant entries) ===" >> "$OUTFILE"
        grep -v "^#\|^$" /etc/hosts >> "$OUTFILE" 2>/dev/null
    fi

    section "Network Statistics"
    if command_exists ss; then
        safe_exec "ss -tuln | head -20"
    elif command_exists netstat; then
        safe_exec "netstat -tuln | head -20"
    fi
}

collect_system_config() {
    section "System Accounts (SAP Related)"
    {
        echo "=== SAP Related Users ==="
        grep -E "(adm|sap)" /etc/passwd || echo "No SAP users found"
        echo ""
        echo "=== All System Users ==="
    } >> "$OUTFILE"
    safe_exec "cat /etc/passwd"

    section "System Groups (SAP Related)"
    {
        echo "=== SAP Related Groups ==="
        grep -E "(sap|dba)" /etc/group || echo "No SAP groups found"
        echo ""
        echo "=== All System Groups ==="
    } >> "$OUTFILE"
    safe_exec "cat /etc/group"

    section "Cron Configuration"
    {
        echo "=== Root Crontab ==="
        crontab -l 2>/dev/null || echo "No root crontab entries"
        echo ""
        echo "=== System Cron Jobs ==="
        ls -la /etc/cron* 2>/dev/null || echo "No system cron directories found"
    } >> "$OUTFILE"

    section "System Services"
    if command_exists systemctl; then
        safe_exec "systemctl list-unit-files --type=service --state=enabled"
        echo "" >> "$OUTFILE"
        echo "=== SAP Related Services ===" >> "$OUTFILE"
        systemctl list-unit-files --type=service | grep -i sap >> "$OUTFILE" 2>/dev/null || echo "No SAP services found" >> "$OUTFILE"
    fi
}

collect_kernel_params() {
    section "Kernel Configuration"
    safe_exec "cat /proc/cmdline"

    section "System Control Configuration (sysctl)"
    if [[ -f /etc/sysctl.conf ]]; then
        echo "=== /etc/sysctl.conf ===" >> "$OUTFILE"
        safe_exec "cat /etc/sysctl.conf"
    fi
    
    echo "" >> "$OUTFILE"
    echo "=== SAP HANA Relevant Kernel Parameters ===" >> "$OUTFILE"
    {
        sysctl kernel.shmmax 2>/dev/null || echo "kernel.shmmax: not set"
        sysctl kernel.shmall 2>/dev/null || echo "kernel.shmall: not set"
        sysctl kernel.shmmni 2>/dev/null || echo "kernel.shmmni: not set"
        sysctl vm.max_map_count 2>/dev/null || echo "vm.max_map_count: not set"
        sysctl net.core.rmem_default 2>/dev/null || echo "net.core.rmem_default: not set"
        sysctl net.core.rmem_max 2>/dev/null || echo "net.core.rmem_max: not set"
        sysctl net.core.wmem_default 2>/dev/null || echo "net.core.wmem_default: not set"
        sysctl net.core.wmem_max 2>/dev/null || echo "net.core.wmem_max: not set"
    } >> "$OUTFILE"

    section "Security Configuration"
    if [[ -f /etc/security/limits.conf ]]; then
        safe_exec "cat /etc/security/limits.conf | grep -v '^#' | grep -v '^$'"
    fi
}

collect_package_info() {
    section "Package Management"
    
    # Detect package manager and OS
    if command_exists zypper; then
        echo "=== SUSE/openSUSE System ===" >> "$OUTFILE"
        safe_exec "zypper --version"
        if command_exists SUSEConnect; then
            safe_exec "SUSEConnect --status"
        fi
        echo "" >> "$OUTFILE"
        echo "=== Installed Repositories ===" >> "$OUTFILE"
        safe_exec "zypper lr"
        
    elif command_exists yum; then
        echo "=== Red Hat/CentOS System ===" >> "$OUTFILE"
        safe_exec "yum --version"
        safe_exec "yum repolist"
        
    elif command_exists dnf; then
        echo "=== Fedora/RHEL 8+ System ===" >> "$OUTFILE"
        safe_exec "dnf --version"
        safe_exec "dnf repolist"
        
    elif command_exists apt; then
        echo "=== Debian/Ubuntu System ===" >> "$OUTFILE"
        safe_exec "apt --version"
        safe_exec "apt list --installed | wc -l"
    fi
}

################################################################################
#                           SAP HANA SPECIFIC ANALYSIS
################################################################################

detect_hana_instances() {
    local sap_dir="/usr/sap"
    local -a hana_sids=()
    
    section "SAP HANA Instance Detection"
    
    if [[ ! -d "$sap_dir" ]]; then
        echo "ERROR: SAP installation directory not found at $sap_dir" >> "$OUTFILE"
        return 1
    fi
    
    # Find HANA instances
    for sid_dir in "$sap_dir"/*; do
        if [[ -d "$sid_dir" && "$(basename "$sid_dir")" != "tmp" ]]; then
            local sid="$(basename "$sid_dir")"
            if ls -1 "$sid_dir"/HDB* >/dev/null 2>&1; then
                hana_sids+=("$sid")
            fi
        fi
    done
    
    if [[ ${#hana_sids[@]} -eq 0 ]]; then
        echo "No SAP HANA instances detected" >> "$OUTFILE"
        return 1
    fi
    
    echo "Detected SAP HANA SIDs: ${hana_sids[*]}" >> "$OUTFILE"
    
    # Analyze each instance
    for sid in "${hana_sids[@]}"; do
        analyze_hana_instance "$sid"
    done
}

analyze_hana_instance() {
    local sid="$1"
    local sap_dir="/usr/sap"
    local sid_dir="$sap_dir/$sid"
    
    section "SAP HANA Instance Analysis: $sid"
    
    # Find instance directory
    local instance_dir
    instance_dir=$(find "$sid_dir" -maxdepth 1 -name "HDB*" -type d | head -1)
    
    if [[ -z "$instance_dir" ]]; then
        echo "ERROR: No HDB instance directory found for SID $sid" >> "$OUTFILE"
        return 1
    fi
    
    local instance_num="$(basename "$instance_dir" | sed 's/HDB//')"
    local hdb_admin="${sid,,}adm"
    
    {
        echo "SID: $sid"
        echo "Instance Number: $instance_num" 
        echo "Instance Directory: $instance_dir"
        echo "Admin User: $hdb_admin"
        echo "Admin Home: $(getent passwd "$hdb_admin" | cut -d: -f6 2>/dev/null || echo "Not found")"
    } >> "$OUTFILE"
    
    # Check if user exists and can execute commands
    if ! id "$hdb_admin" >/dev/null 2>&1; then
        echo "WARNING: Admin user $hdb_admin not found" >> "$OUTFILE"
        return 1
    fi
    
    # HANA Version Information
    section "HANA Version Information ($sid)"
    execute_as_hana_user "$hdb_admin" "HDB version" "HANA version check"
    
    # HANA Services Status
    section "HANA Services Status ($sid)"
    execute_as_hana_user "$hdb_admin" "HDB info" "HANA services status"
    
    # HANA Configuration
    section "HANA Configuration Parameters ($sid)"
    execute_as_hana_user "$hdb_admin" "hdbparam" "HANA parameter dump"
    
    # HANA Landscape
    section "HANA Landscape Configuration ($sid)"
    local landscape_script="$instance_dir/exe/python_support/landscapeHostConfiguration.py"
    if [[ -f "$landscape_script" ]]; then
        execute_as_hana_user "$hdb_admin" "python $landscape_script" "Landscape configuration"
    else
        echo "Landscape script not found at $landscape_script" >> "$OUTFILE"
    fi
    
    # HANA System Overview
    section "HANA System Overview ($sid)"
    local overview_script="$instance_dir/exe/python_support/systemOverview.py"
    if [[ -f "$overview_script" ]]; then
        execute_as_hana_user "$hdb_admin" "python $overview_script" "System overview"
    fi
    
    # HANA Hardware Check
    section "HANA Hardware Validation ($sid)"
    local hw_check_script="$instance_dir/exe/python_support/checkHardware.py"
    if [[ -f "$hw_check_script" ]]; then
        execute_as_hana_user "$hdb_admin" "python $hw_check_script -m details" "Hardware check"
    fi
    
    # HANA Memory Information
    section "HANA Memory Analysis ($sid)"
    {
        echo "=== System Memory ==="
        free -h
        echo ""
        echo "=== HANA Memory Information ==="
    } >> "$OUTFILE"
    execute_as_hana_user "$hdb_admin" "HDB info | grep -i memory" "HANA memory status"
    
    # HANA File System Analysis
    section "HANA File System Layout ($sid)"
    {
        echo "=== HANA Data Directories ==="
        find "/hana" -maxdepth 3 -name "*$sid*" -type d 2>/dev/null | sort || echo "No /hana directories found"
        echo ""
        echo "=== SAP Installation Files ==="
        ls -la "$sid_dir" 2>/dev/null
        echo ""
        echo "=== HANA Volume Usage ==="
        df -h | grep -E "(hana|sap)" || echo "No HANA-specific mount points found"
    } >> "$OUTFILE"
}

# Safe execution as HANA user with error handling
execute_as_hana_user() {
    local user="$1"
    local command="$2" 
    local description="$3"
    
    log_debug "Executing as $user: $command"
    
    if su - "$user" -c "$command" >> "$OUTFILE" 2>&1; then
        log_debug "Successfully executed: $description"
    else
        echo "ERROR: Failed to execute $description as user $user" >> "$OUTFILE"
        log_warn "Failed to execute: $description"
    fi
}

# Main execution function
main() {
    local start_time
    start_time=$(date +%s)
    
    # Validate environment
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root for complete system analysis"
        exit 1
    fi
    
    log_info "Starting SAP HANA System Report Generation"
    log_info "Report will be saved to: $OUTFILE"
    
    # Initialize report
    init_report
    
    # Collect system information
    collect_system_info
    collect_hardware_info  
    collect_storage_info
    collect_network_info
    collect_system_config
    collect_kernel_params
    collect_package_info
    
    # SAP HANA specific analysis
    detect_hana_instances
    
    # Finalize report
    local end_time
    end_time=$(date +%s)
    local duration=$((end_time - start_time))
    
    cat >> "$OUTFILE" << EOF

################################################################################
# REPORT GENERATION COMPLETED
################################################################################
Report generated in: ${duration} seconds
Report file: $OUTFILE
Report size: $(du -h "$OUTFILE" | cut -f1)
Generated by: SAP HANA System Report Generator v2.0

EOF

    log_info "Report generation completed successfully"
    log_info "Report saved to: $OUTFILE"
    log_info "Generation time: ${duration} seconds"
    
    # Display summary
    echo -e "\n${GREEN}===== REPORT SUMMARY =====${NC}"
    echo "Report Location: $OUTFILE"
    echo "Report Size: $(du -h "$OUTFILE" | cut -f1)"
    echo "Generation Time: ${duration} seconds"
    echo "Timestamp: $(date)"
}

# Script execution
main "$@"