#!/bin/bash

# SAP HANA Full System Report Generator
# Version: 2.0
# Description: Comprehensive system and SAP HANA analysis tool

set -euo pipefail  # Exit on error, undefined variables, and pipe failures

# Configuration
readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly HOSTNAME="$(hostname -s)"
readonly TIMESTAMP="$(date +%F_%H-%M-%S)"
readonly OUTDIR="${REPORT_DIR:-/root}"
readonly OUTFILE="${OUTDIR}/sap-report-${HOSTNAME}-${TIMESTAMP}.txt"
readonly LOG_LEVEL="${LOG_LEVEL:-INFO}"

# Colors for output
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly BLUE='\033[0;34m'
readonly NC='\033[0m' # No Color

# Initialize report
init_report() {
    # Create output directory if it doesn't exist
    mkdir -p "$OUTDIR"

    # Initialize report file
    cat > "$OUTFILE" << EOF
================================================================================
                    FULL SAP HANA SYSTEM REPORT
================================================================================
Host: $(hostname -f)
Generated on: $(date)
Generated by: $(whoami)
Script Version: 2.0
Report File: $OUTFILE
================================================================================

EOF
}

# Logging functions
log_info() {
    [[ "$LOG_LEVEL" =~ ^(DEBUG|INFO)$ ]] && echo -e "${GREEN}[INFO]${NC} $*" >&2
}

log_warn() {
    [[ "$LOG_LEVEL" =~ ^(DEBUG|INFO|WARN)$ ]] && echo -e "${YELLOW}[WARN]${NC} $*" >&2
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $*" >&2
}

log_debug() {
    [[ "$LOG_LEVEL" == "DEBUG" ]] && echo -e "${BLUE}[DEBUG]${NC} $*" >&2
}

# Progress indicator
show_progress() {
    echo -e "${BLUE}[PROGRESS]${NC} $*" >&2
}

# Section header function with improved formatting
section() {
    local title="$1"
    local timestamp="$(date '+%Y-%m-%d %H:%M:%S')"

    cat >> "$OUTFILE" << EOF

################################################################################
# $title
# Collected at: $timestamp
################################################################################

EOF
    show_progress "Collecting: $title"
}

# Safe command execution with error handling
safe_exec() {
    local cmd="$*"
    local result

    log_debug "Executing: $cmd"

    # Temporarily disable exit on error for this command
    set +e
    result=$(eval "$cmd" 2>&1)
    local exit_code=$?
    set -e

    if [[ $exit_code -eq 0 ]]; then
        echo "$result" >> "$OUTFILE"
        return 0
    else
        echo "ERROR: Command failed - $cmd (exit code: $exit_code)" >> "$OUTFILE"
        echo "Error output: $result" >> "$OUTFILE"
        log_warn "Command failed: $cmd"
        return 1
    fi
}

# Check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Recovery wrapper function
run_with_recovery() {
    local func_name="$1"
    local section_name="$2"
    local -n failed_array="$3"

    show_progress "Collecting: $section_name"

    # Disable exit on error temporarily
    set +e

    if ! "$func_name"; then
        failed_array+=("$section_name")
        log_error "Failed to collect: $section_name"

        # Add error section to report
        {
            echo ""
            echo "################################################################################"
            echo "# ERROR: $section_name Collection Failed"
            echo "# Collected at: $(date '+%Y-%m-%d %H:%M:%S')"
            echo "################################################################################"
            echo ""
            echo "An error occurred while collecting $section_name."
            echo "This may be due to missing commands, insufficient permissions, or system issues."
            echo "The report generation will continue with remaining sections."
            echo ""
        } >> "$OUTFILE"
    else
        log_info "Successfully collected: $section_name"
    fi

    # Re-enable exit on error
    set -e
}

# System Information Collection Functions
collect_system_info() {
    section "System Information Summary"
    {
        echo "Hostname (short): $(hostname -s)"
        echo "Hostname (FQDN): $(hostname -f 2>/dev/null || hostname -s)"
        echo "Operating System: $(get_os_info)"
        echo "Kernel Version: $(uname -r)"
        echo "Architecture: $(uname -m)"
        echo "System Uptime: $(uptime -p 2>/dev/null || uptime | cut -d',' -f1)"
        echo "Current User: $(whoami)"
        local load_avg=$(uptime | grep -o 'load average:.*' | cut -d':' -f2 || echo " N/A")
        echo "System Load:$load_avg"
    } >> "$OUTFILE"

    section "Detailed OS Information"
    if [[ -f /etc/os-release ]]; then
        safe_exec "cat /etc/os-release"
    elif [[ -f /etc/redhat-release ]]; then
        safe_exec "cat /etc/redhat-release"
    elif [[ -f /etc/SuSE-release ]]; then
        safe_exec "cat /etc/SuSE-release"
    else
        echo "OS release information not found" >> "$OUTFILE"
    fi

    section "Kernel Information"
    safe_exec "uname -a"

    section "System Date and Time"
    safe_exec "date"
    if command_exists timedatectl; then
        safe_exec "timedatectl"
    fi

    section "Timezone Configuration"
    if [[ -f /etc/timezone ]]; then
        safe_exec "cat /etc/timezone"
    elif [[ -L /etc/localtime ]]; then
        safe_exec "ls -la /etc/localtime"
    else
        echo "Timezone information not available via standard files" >> "$OUTFILE"
        safe_exec "date +%Z"
    fi
}

# Helper function to get OS info
get_os_info() {
    if [[ -f /etc/os-release ]]; then
        . /etc/os-release
        echo "$PRETTY_NAME"
    elif [[ -f /etc/redhat-release ]]; then
        cat /etc/redhat-release
    elif [[ -f /etc/SuSE-release ]]; then
        head -n1 /etc/SuSE-release
    else
        echo "Unknown Linux Distribution"
    fi
}

collect_hardware_info() {
    section "Hardware Summary"
    {
        echo "CPU Model: $(grep 'model name' /proc/cpuinfo | head -1 | cut -d: -f2 | sed 's/^ *//')"
        echo "CPU Cores: $(nproc)"
        echo "Total Memory: $(free -h | awk '/^Mem:/ {print $2}')"
        echo "Available Memory: $(free -h | awk '/^Mem:/ {print $7}')"
    } >> "$OUTFILE"

    section "Detailed CPU Information"
    if command_exists lscpu; then
        safe_exec "lscpu"
    else
        safe_exec "cat /proc/cpuinfo"
    fi

    section "Memory Information"
    safe_exec "free -h"
    echo "" >> "$OUTFILE"
    safe_exec "cat /proc/meminfo | head -20"

    section "NUMA Configuration"
    if command_exists numactl; then
        safe_exec "numactl --hardware"
        safe_exec "numactl --show"
    else
        echo "numactl command not available" >> "$OUTFILE"
    fi

    section "HugePages Configuration"
    safe_exec "grep -E '^HugePages\|^Hugepagesize' /proc/meminfo || echo 'No HugePages configuration found in /proc/meminfo'"

    section "Transparent HugePages Status"
    if [[ -f /sys/kernel/mm/transparent_hugepage/enabled ]]; then
        echo "THP Enabled: $(cat /sys/kernel/mm/transparent_hugepage/enabled)" >> "$OUTFILE"
    fi
    if [[ -f /sys/kernel/mm/transparent_hugepage/defrag ]]; then
        echo "THP Defrag: $(cat /sys/kernel/mm/transparent_hugepage/defrag)" >> "$OUTFILE"
    fi

    section "I/O Scheduler Configuration"
    for device in /sys/block/*/queue/scheduler; do
        if [[ -f "$device" ]]; then
            block_device=$(echo "$device" | cut -d/ -f4)
            echo "Device $block_device: $(cat "$device")" >> "$OUTFILE"
        fi
    done

    section "Hardware Details"
    if command_exists dmidecode; then
        safe_exec "dmidecode -t system | head -20"
    fi
}

collect_storage_info() {
    section "Storage Overview"
    safe_exec "df -h"
    echo "" >> "$OUTFILE"
    safe_exec "lsblk -f"

    section "Filesystem Table (fstab)"
    safe_exec "cat /etc/fstab"

    section "Mount Points"
    safe_exec "mount | column -t"

    section "LVM Configuration"
    if command_exists pvs; then
        safe_exec "pvs -v"
        safe_exec "vgs -v"
        safe_exec "lvs -v"
    else
        echo "LVM tools not available" >> "$OUTFILE"
    fi

    section "Storage Device Information"
    safe_exec "lsblk -D"  # Show discard capabilities

    section "Disk I/O Statistics"
    if command_exists iostat; then
        safe_exec "iostat -x 1 3"
    fi

    section "SAP HANA Relevant Storage"
    {
        echo "=== HANA Data and Log Directories ==="
        find /hana -maxdepth 3 -type d 2>/dev/null | head -20 || echo "No /hana directory found"
        echo ""
        echo "=== SAP Installation Directory ==="
        ls -la /usr/sap/ 2>/dev/null || echo "No /usr/sap directory found"
    } >> "$OUTFILE"
}

collect_network_info() {
    section "Network Interface Summary"
    {
        echo "=== Active Network Interfaces ==="
        ip -o link show | awk '{print $2, $3, $9}'
        echo ""
        echo "=== IP Address Summary ==="
        ip -o addr show | grep 'inet ' | awk '{print $2, $4}'
    } >> "$OUTFILE"

    section "Network Interface Details"
    if command_exists ip; then
        safe_exec "ip addr show"
    else
        safe_exec "ifconfig -a"
    fi

    section "Routing Table"
    if command_exists ip; then
        safe_exec "ip route show"
        safe_exec "ip -6 route show"
    else
        safe_exec "route -n"
    fi

    section "Network Bonding Configuration"
    local bond_found=false
    for bond_file in /proc/net/bonding/bond*; do
        if [[ -f "$bond_file" ]]; then
            bond_found=true
            echo "=== Bond Interface: $(basename "$bond_file") ===" >> "$OUTFILE"
            safe_exec "cat $bond_file"
        fi
    done
    [[ "$bond_found" == false ]] && echo "No bonded interfaces found" >> "$OUTFILE"

    section "DNS Configuration"
    safe_exec "cat /etc/resolv.conf"
    if [[ -f /etc/hosts ]]; then
        echo "" >> "$OUTFILE"
        echo "=== Hosts File (relevant entries) ===" >> "$OUTFILE"
        grep -v "^#\|^$" /etc/hosts >> "$OUTFILE" 2>/dev/null
    fi

    section "Network Statistics"
    if command_exists ss; then
        safe_exec "ss -tuln | head -20"
    elif command_exists netstat; then
        safe_exec "netstat -tuln | head -20"
    fi
}

collect_hardware_components() {
    section "BIOS and System Firmware"
    {
        echo "=== BIOS/UEFI Information ==="
        if command_exists dmidecode; then
            dmidecode -t bios 2>/dev/null | grep -E "(Vendor|Version|Release Date|BIOS Revision)" || echo "BIOS information not available"
            echo ""
            echo "=== System Information ==="
            dmidecode -t system 2>/dev/null | grep -E "(Manufacturer|Product Name|Version|Serial Number)" || echo "System information not available"
            echo ""
            echo "=== Motherboard Information ==="
            dmidecode -t baseboard 2>/dev/null | grep -E "(Manufacturer|Product Name|Version|Serial Number)" || echo "Motherboard information not available"
        else
            echo "dmidecode not available - cannot retrieve BIOS/system information"
        fi
    } >> "$OUTFILE"

    section "Disk Controllers and Storage Firmware"
    {
        echo "=== Storage Controllers (PCI) ==="
        if command_exists lspci; then
            lspci -v | grep -A 10 -i -E "(storage controller|sata|scsi|raid|nvme controller)" | head -50 || echo "No storage controllers found"
        else
            echo "lspci not available"
        fi
        
        echo ""
        echo "=== Disk Drive Firmware Versions ==="
        if command_exists smartctl; then
            for device in $(lsblk -d -n -o NAME | grep -E "^(sd|nvme|hd)"); do
                if [[ -e "/dev/$device" ]]; then
                    echo "--- Storage Device: /dev/$device ---"
                    smartctl -i "/dev/$device" 2>/dev/null | grep -E "(Device Model|Model Number|Serial Number|Firmware Version|User Capacity)" | head -10 || echo "SMART info not available for /dev/$device"
                    echo ""
                fi
            done
        else
            echo "smartctl not available for storage firmware check"
        fi

        echo "=== NVMe Storage Detailed Info ==="
        if command_exists nvme; then
            for nvme_dev in /dev/nvme*n1; do
                if [[ -e "$nvme_dev" ]]; then
                    echo "--- NVMe Device: $nvme_dev ---"
                    {
                        echo "Model: $(nvme id-ctrl "$nvme_dev" 2>/dev/null | grep '^mn ' | cut -d: -f2 | xargs || echo 'N/A')"
                        echo "Serial: $(nvme id-ctrl "$nvme_dev" 2>/dev/null | grep '^sn ' | cut -d: -f2 | xargs || echo 'N/A')"
                        echo "Firmware: $(nvme id-ctrl "$nvme_dev" 2>/dev/null | grep '^fr ' | cut -d: -f2 | xargs || echo 'N/A')"
                    } || echo "NVMe info not available for $nvme_dev"
                    echo ""
                fi
            done
        else
            echo "nvme command not available"
        fi
    } >> "$OUTFILE"

    section "Network Controllers and Firmware"
    {
        echo "=== Network Controllers (PCI) ==="
        if command_exists lspci; then
            lspci -v | grep -A 8 -i "ethernet\|network" | head -40 || echo "No network controllers found"
        fi

        echo ""
        echo "=== Network Interface Driver and Firmware Details ==="
        for iface in $(ls /sys/class/net/ 2>/dev/null | grep -v -E "^(lo|bond|br|docker|vir)" | head -10); do
            if [[ -d "/sys/class/net/$iface/device" ]]; then
                echo "--- Network Interface: $iface ---"
                
                # Driver information
                if [[ -L "/sys/class/net/$iface/device/driver" ]]; then
                    driver_path=$(readlink "/sys/class/net/$iface/device/driver" 2>/dev/null)
                    driver_name=$(basename "$driver_path" 2>/dev/null || echo "Unknown")
                    echo "Driver: $driver_name"
                fi
                
                # Hardware details
                if [[ -f "/sys/class/net/$iface/device/vendor" ]] && [[ -f "/sys/class/net/$iface/device/device" ]]; then
                    vendor_id=$(cat "/sys/class/net/$iface/device/vendor" 2>/dev/null || echo "Unknown")
                    device_id=$(cat "/sys/class/net/$iface/device/device" 2>/dev/null || echo "Unknown")
                    echo "Hardware ID: $vendor_id:$device_id"
                fi
                
                # Detailed driver and firmware info via ethtool
                if command_exists ethtool && [[ "$iface" != "lo" ]]; then
                    ethtool -i "$iface" 2>/dev/null | grep -E "(driver|version|firmware)" || echo "ethtool info not available"
                fi
                echo ""
            fi
        done
    } >> "$OUTFILE"

    section "HBA (Host Bus Adapter) Information"
    {
        echo "=== Fibre Channel HBAs ==="
        if [[ -d /sys/class/fc_host ]]; then
            for hba in /sys/class/fc_host/host*; do
                if [[ -d "$hba" ]]; then
                    hba_name=$(basename "$hba")
                    echo "--- HBA: $hba_name ---"
                    echo "Node Name: $(cat "$hba/node_name" 2>/dev/null || echo 'N/A')"
                    echo "Port Name: $(cat "$hba/port_name" 2>/dev/null || echo 'N/A')"
                    echo "Port State: $(cat "$hba/port_state" 2>/dev/null || echo 'N/A')"
                    echo "Speed: $(cat "$hba/speed" 2>/dev/null || echo 'N/A')"
                    echo "Supported Speeds: $(cat "$hba/supported_speeds" 2>/dev/null || echo 'N/A')"
                    echo ""
                fi
            done
        else
            echo "No Fibre Channel HBAs found"
        fi

        echo "=== SCSI Host Adapters ==="
        if command_exists lspci; then
            lspci -v | grep -A 5 -i -E "(fibre channel|scsi|hba)" || echo "No SCSI/FC controllers found"
        fi

        echo ""
        echo "=== HBA Driver Modules ==="
        {
            echo "Loaded HBA drivers:"
            lsmod | grep -E "(qla|lpfc|mpt|bnx2fc|fnic)" || echo "No common HBA drivers loaded"
            echo ""
            echo "HBA driver details:"
            for module in qla2xxx lpfc mpt3sas bnx2fc fnic; do
                if lsmod | grep -q "^$module "; then
                    modinfo "$module" 2>/dev/null | grep -E "(version|description)" || echo "$module info not available"
                    echo ""
                fi
            done
        }
    } >> "$OUTFILE"

    section "RAID Controller Information"
    {
        echo "=== Hardware RAID Controllers ==="
        if command_exists lspci; then
            lspci -v | grep -A 8 -i "raid" || echo "No RAID controllers found via PCI scan"
        fi

        echo ""
        echo "=== LSI/Broadcom RAID (MegaRAID) ==="
        if command_exists megacli || command_exists megacli64 || command_exists storcli || command_exists storcli64; then
            for cmd in megacli megacli64 storcli storcli64; do
                if command_exists "$cmd"; then
                    echo "Using $cmd:"
                    case $cmd in
                        *megacli*)
                            "$cmd" -AdpAllInfo -aAll 2>/dev/null | grep -E "(Product Name|FW Package|BIOS|Serial)" | head -10 || echo "$cmd query failed"
                            ;;
                        *storcli*)
                            "$cmd" /c0 show 2>/dev/null | grep -E "(Product Name|Firmware|BIOS)" | head -10 || echo "$cmd query failed"
                            ;;
                    esac
                    echo ""
                    break
                fi
            done
        else
            echo "No LSI/Broadcom RAID utilities found"
        fi

        echo "=== HP Smart Array Controllers ==="
        if command_exists hpacucli || command_exists hpssacli || command_exists ssacli; then
            for cmd in ssacli hpssacli hpacucli; do
                if command_exists "$cmd"; then
                    echo "Using $cmd:"
                    "$cmd" ctrl all show 2>/dev/null | head -10 || echo "$cmd query failed"
                    "$cmd" ctrl all show detail 2>/dev/null | grep -E "(Controller|Firmware|Hardware)" | head -10 || echo "Detail query failed"
                    echo ""
                    break
                fi
            done
        else
            echo "No HP Smart Array utilities found"
        fi

        echo "=== Dell PERC Controllers ==="
        if command_exists omreport; then
            omreport storage controller 2>/dev/null | grep -E "(Name|Firmware|Driver)" || echo "omreport query failed"
        elif command_exists perccli || command_exists perccli64; then
            for cmd in perccli perccli64; do
                if command_exists "$cmd"; then
                    "$cmd" /c0 show 2>/dev/null | grep -E "(Product Name|Firmware|Package)" | head -10 || echo "$cmd query failed"
                    break
                fi
            done
        else
            echo "No Dell PERC utilities found"
        fi

        echo ""
        
    } >> "$OUTFILE"

    section "Hardware Component Summary"
    {
        echo "=== System Component Overview ==="
        echo "BIOS/UEFI: $(dmidecode -t bios 2>/dev/null | grep "Version" | head -1 | cut -d: -f2 | xargs || echo 'Unknown')"
        echo "System: $(dmidecode -t system 2>/dev/null | grep "Product Name" | head -1 | cut -d: -f2 | xargs || echo 'Unknown')"
        echo ""
        echo "Storage Devices: $(lsblk -d | grep -E "^(sd|nvme)" | wc -l) detected"
        echo "Network Interfaces: $(ls /sys/class/net/ 2>/dev/null | grep -v lo | wc -l) detected"
        echo "HBA Controllers: $(ls /sys/class/fc_host/ 2>/dev/null | wc -l) detected"
        echo ""
        echo "Critical Driver Status:"
        echo "- Storage drivers loaded: $(lsmod | grep -E "(ahci|nvme|mpt|qla|lpfc)" | wc -l)"
        echo "- Network drivers loaded: $(lsmod | grep -E "(e1000|igb|ixgbe|i40e|mlx)" | wc -l)"
        echo "- RAID drivers loaded: $(lsmod | grep -E "(raid|md)" | wc -l)"
    } >> "$OUTFILE"
}

collect_system_config() {
    section "System Accounts (SAP Related)"
    {
        echo "=== SAP Related Users ==="
        grep -iE "adm|sap" /etc/passwd || echo "No SAP users found"
        echo ""
        echo "=== All System Users ==="
    } >> "$OUTFILE"
    safe_exec "cat /etc/passwd"

    section "System Groups (SAP Related)"
    {
        echo "=== SAP Related Groups ==="
        grep -E "adm|sap" /etc/group || echo "No SAP groups found"
        echo ""
        echo "=== All System Groups ==="
    } >> "$OUTFILE"
    safe_exec "cat /etc/group"

    section "Cron Configuration"
    {
        echo "=== Root Crontab ==="
        crontab -l 2>/dev/null || echo "No root crontab entries"
        echo ""
        echo "=== System Cron Jobs ==="
        ls -la /etc/cron* 2>/dev/null || echo "No system cron directories found"
    } >> "$OUTFILE"

    section "System Services"
    if command_exists systemctl; then
        safe_exec "systemctl list-unit-files --type=service --state=enabled"
        echo "" >> "$OUTFILE"
        echo "=== SAP Related Services ===" >> "$OUTFILE"
        systemctl list-unit-files --type=service | grep -i sap >> "$OUTFILE" 2>/dev/null || echo "No SAP services found" >> "$OUTFILE"
    fi
}

collect_kernel_params() {
    section "Kernel Configuration"
    safe_exec "cat /proc/cmdline"

    section "System Control Configuration (sysctl)"
    if [[ -f /etc/sysctl.conf ]]; then
        echo "=== /etc/sysctl.conf ===" >> "$OUTFILE"
        safe_exec "cat /etc/sysctl.conf"
    fi

    echo "" >> "$OUTFILE"
    echo "=== SAP HANA Relevant Kernel Parameters ===" >> "$OUTFILE"
    {
        sysctl kernel.shmmax 2>/dev/null || echo "kernel.shmmax: not set"
        sysctl kernel.shmall 2>/dev/null || echo "kernel.shmall: not set"
        sysctl kernel.shmmni 2>/dev/null || echo "kernel.shmmni: not set"
        sysctl vm.max_map_count 2>/dev/null || echo "vm.max_map_count: not set"
        sysctl net.core.rmem_default 2>/dev/null || echo "net.core.rmem_default: not set"
        sysctl net.core.rmem_max 2>/dev/null || echo "net.core.rmem_max: not set"
        sysctl net.core.wmem_default 2>/dev/null || echo "net.core.wmem_default: not set"
        sysctl net.core.wmem_max 2>/dev/null || echo "net.core.wmem_max: not set"
    } >> "$OUTFILE"

    section "Security Configuration"
    if [[ -f /etc/security/limits.conf ]]; then
        safe_exec "cat /etc/security/limits.conf | grep -v '^#' | grep -v '^$'"
    fi
}

collect_package_info() {
    section "Package Management"

    # Detect package manager and OS
    if command_exists zypper; then
        echo "=== SUSE/openSUSE System ===" >> "$OUTFILE"
        safe_exec "zypper --version"
        if command_exists SUSEConnect; then
            safe_exec "SUSEConnect --status"
        fi
        echo "" >> "$OUTFILE"
        echo "=== Installed Repositories ===" >> "$OUTFILE"
        safe_exec "zypper lr"

    elif command_exists yum; then
        echo "=== Red Hat/CentOS System ===" >> "$OUTFILE"
        safe_exec "yum --version"
        safe_exec "yum repolist"

    elif command_exists dnf; then
        echo "=== Fedora/RHEL 8+ System ===" >> "$OUTFILE"
        safe_exec "dnf --version"
        safe_exec "dnf repolist"

    elif command_exists apt; then
        echo "=== Debian/Ubuntu System ===" >> "$OUTFILE"
        safe_exec "apt --version"
        safe_exec "apt list --installed | wc -l"
    fi
}

################################################################################
#                           SAP HANA SPECIFIC ANALYSIS
################################################################################

detect_hana_instances() {
    local sap_dir="/usr/sap"
    local -a hana_sids=()

    section "SAP HANA Instance Detection"

    echo "" >> "$OUTFILE"
    echo "=== Checking for HANA admin users ===" >> "$OUTFILE"
    local user_sids
    user_sids=$(getent passwd | awk -F':' '/SAP HANA Database System Administrator/ {print $1}' | sed 's/adm$//' | tr '[:lower:]' '[:upper:]' 2>/dev/null)

    if [[ -n "$user_sids" ]]; then
        while IFS= read -r sid; do
            if [[ -n "$sid" && ! " ${hana_sids[@]} " =~ " ${sid} " ]]; then
                # Verify this is actually a HANA SID by checking for HANA-specific directories
                local user_home
                user_home=$(getent passwd "${sid,,}adm" 2>/dev/null | cut -d':' -f6)
                if [[ -n "$user_home" && -d "$user_home" ]]; then
                    # Check for HANA indicators in multiple locations
                    if find "$user_home" -name "*.py" -path "*/python_support/*" 2>/dev/null | head -1 | grep -q . || \
                       find "/usr/sap/$sid" -name "hdbsql" 2>/dev/null | head -1 | grep -q . || \
                       find "/usr/sap/$sid" -name "HDB*" -type d 2>/dev/null | head -1 | grep -q . || \
                       [[ -d "/usr/sap/$sid" && -n "$(ls -A "/usr/sap/$sid" 2>/dev/null)" ]]; then
                        hana_sids+=("$sid")
                        echo "Found HANA SID via user check: $sid (user: ${sid,,}adm)" >> "$OUTFILE"
                    fi
                fi
            fi
        done <<< "$user_sids"
    else
        echo "No potential HANA admin users found" >> "$OUTFILE"
    fi

    # Additional check for directories in /usr/sap that might contain HANA instances
    if [[ -d "$sap_dir" ]]; then
        echo "" >> "$OUTFILE"
        echo "=== Checking SAP directories ===" >> "$OUTFILE"
        for sid_dir in "$sap_dir"/*; do
            if [[ -d "$sid_dir" ]]; then
                local sid_name="$(basename "$sid_dir")"
                if [[ ! " ${hana_sids[@]} " =~ " ${sid_name} " && -n "$(find "$sid_dir" -name "HDB*" -type d 2>/dev/null | head -1)" ]]; then
                    hana_sids+=("$sid_name")
                    echo "Found HANA SID via directory check: $sid_name" >> "$OUTFILE"
                fi
            fi
        done
    fi


    echo "" >> "$OUTFILE"
    echo "Detected SAP HANA SIDs: ${hana_sids[*]}" >> "$OUTFILE"
    echo "" >> "$OUTFILE"

    # Analyze each instance
    for sid in "${hana_sids[@]}"; do
        analyze_hana_instance "$sid" || log_warn "Failed to analyze HANA instance $sid"
    done
}

analyze_hana_instance() {
    local sid="$1"
    local sap_dir="/hana/shared"
    local sid_dir="$sap_dir/$sid"

    section "SAP HANA Instance Analysis: $sid"

    # Find instance directory
    local instance_dir
    instance_dir=$(find "$sid_dir" -maxdepth 1 -name "HDB*" -type d | head -1)

    if [[ -z "$instance_dir" ]]; then
        echo "ERROR: No HDB instance directory found for SID $sid" >> "$OUTFILE"
        return 1
    fi

    local instance_num="$(basename "$instance_dir" | sed 's/HDB//')"
    local hdb_admin="${sid,,}adm"

    {
        echo "SID: $sid"
        echo "Instance Number: $instance_num"
        echo "Instance Directory: $instance_dir"
        echo "Admin User: $hdb_admin"
        echo "Admin Home: $(getent passwd "$hdb_admin" | cut -d: -f6 2>/dev/null || echo "Not found")"
    } >> "$OUTFILE"

    # Check if user exists and can execute commands
    if ! id "$hdb_admin" >/dev/null 2>&1; then
        echo "WARNING: Admin user $hdb_admin not found" >> "$OUTFILE"
        return 1
    fi

    # HANA Version Information
    section "HANA Version Information ($sid)"
    execute_as_hana_user "$hdb_admin" "HDB version" "HANA version check"

    # HANA Services Status
    section "HANA Services Status ($sid)"
    execute_as_hana_user "$hdb_admin" "HDB info" "HANA services status"

    # HANA Configuration
    section "HANA Configuration Parameters ($sid)"
    local config_file="/hana/shared/$sid/global/hdb/custom/config/global.ini"
    if [[ -f "$config_file" ]]; then
        echo "=== HANA Global Configuration ===" >> "$OUTFILE"
        safe_exec "cat $config_file"
    else
        echo "HANA configuration file not found at $config_file" >> "$OUTFILE"
    fi

    # HANA Landscape
    section "HANA Landscape Configuration ($sid)"
    local landscape_script="$instance_dir/exe/python_support/landscapeHostConfiguration.py"
    if [[ -f "$landscape_script" ]]; then
        execute_as_hana_user "$hdb_admin" "python $landscape_script" "Landscape configuration"
    else
        echo "Landscape script not found at $landscape_script" >> "$OUTFILE"
    fi

    # HANA System Overview
    section "HANA System Overview ($sid)"
    local overview_script="$instance_dir/exe/python_support/systemOverview.py"
    if [[ -f "$overview_script" ]]; then
        execute_as_hana_user "$hdb_admin" "python $overview_script" "System overview"
    fi

    # HANA Memory Information
    section "HANA Memory Analysis ($sid)"
    {
        echo "=== System Memory ==="
        free -h
        echo ""
        echo "=== HANA Memory Information ==="
    } >> "$OUTFILE"
    execute_as_hana_user "$hdb_admin" "HDB info | grep -i memory" "HANA memory status"

    # HANA File System Analysis
    section "HANA File System Layout ($sid)"
    {
        echo "=== HANA Data Directories ==="
        find "/hana" -maxdepth 3 -name "*$sid*" -type d 2>/dev/null | sort || echo "No /hana directories found"
        echo ""
        echo "=== SAP Installation Files ==="
        ls -la "$sid_dir" 2>/dev/null
        echo ""
        echo "=== HANA Volume Usage ==="
        df -h | grep -E "hana|sap" || echo "No HANA-specific mount points found"
    } >> "$OUTFILE"
}

# Safe execution as HANA user with error handling
execute_as_hana_user() {
    local user="$1"
    local command="$2"
    local description="$3"

    log_debug "Executing as $user: $command"

    if su - "$user" -c "$command" >> "$OUTFILE" 2>&1; then
        log_debug "Successfully executed: $description"
    else
        echo "ERROR: Failed to execute $description as user $user" >> "$OUTFILE"
        log_warn "Failed to execute: $description"
    fi
}

# Main execution function
main() {
    local start_time
    start_time=$(date +%s)

    # Validate environment
    if [[ $EUID -ne 0 && "${TEST_MODE:-false}" != "true" ]]; then
        log_error "This script must be run as root for complete system analysis"
        log_info "Use -t or --test flag to run in test mode without root privileges"
        exit 1
    fi

    if [[ "${TEST_MODE:-false}" == "true" ]]; then
        log_warn "Running in TEST MODE - some information may be incomplete"
    fi

    # Pre-flight checks
    log_info "Starting SAP HANA System Report Generator v2.0"
    log_info "Report will be saved to: $OUTFILE"

    # Validate output directory
    if ! mkdir -p "$OUTDIR" 2>/dev/null; then
        log_error "Cannot create output directory: $OUTDIR"
        exit 1
    fi

    # Check available disk space
    local available_space
    available_space=$(df "$OUTDIR" | awk 'NR==2 {print $4}')
    if [[ $available_space -lt 100000 ]]; then  # Less than ~100MB
        log_warn "Low disk space in output directory: $OUTDIR"
    fi

    # Basic system validation
    log_info "System validation: $(uname -s) $(uname -r) $(uname -m)"
    log_info "User context: $(whoami) (UID: $EUID)"

    # Initialize report
    init_report

    # Collect system information with comprehensive error handling
    local -a failed_sections=()

    run_with_recovery "collect_system_info" "System Information" failed_sections
    run_with_recovery "collect_hardware_info" "Hardware Information" failed_sections
    run_with_recovery "collect_hardware_components" "Hardware Components & Firmware" failed_sections
    run_with_recovery "collect_storage_info" "Storage Information" failed_sections
    run_with_recovery "collect_network_info" "Network Information" failed_sections
    run_with_recovery "collect_system_config" "System Configuration" failed_sections
    run_with_recovery "collect_kernel_params" "Kernel Parameters" failed_sections
    run_with_recovery "collect_package_info" "Package Information" failed_sections
    run_with_recovery "detect_hana_instances" "SAP HANA Analysis" failed_sections

    # Report failed sections
    if [[ ${#failed_sections[@]} -gt 0 ]]; then
        section "Report Generation Issues"
        {
            echo "The following sections encountered errors during collection:"
            printf " - %s\n" "${failed_sections[@]}"
            echo ""
            echo "Despite these issues, the report has been completed with available information."
        } >> "$OUTFILE"
    fi

    # Finalize report
    local end_time
    end_time=$(date +%s)
    local duration=$((end_time - start_time))

    # Ensure report is properly completed
    local report_size="$(du -h "$OUTFILE" 2>/dev/null | cut -f1 || echo 'Unknown')"
    local line_count="$(wc -l < "$OUTFILE" 2>/dev/null || echo 'Unknown')"

    cat >> "$OUTFILE" << EOF

################################################################################
# REPORT GENERATION COMPLETED SUCCESSFULLY
################################################################################
Generation Details:
  - Start Time: $(date -d "@$start_time" 2>/dev/null || echo 'Unknown')
  - End Time: $(date)
  - Duration: ${duration} seconds
  - Report File: $OUTFILE
  - Report Size: $report_size
  - Report Lines: $line_count
  - Generated By: SAP HANA System Report Generator v2.0
  - Hostname: $(hostname -f)
  - Operating System: $(get_os_info)
  - Kernel: $(uname -r)

Report Sections:
  [OK] System Information
  [OK] Hardware Details
  [OK] Storage Configuration
  [OK] Network Setup
  [OK] System Configuration
  [OK] Kernel Parameters
  [OK] Package Information
  [OK] SAP HANA Analysis

For support or questions about this report, please contact your system administrator.
################################################################################

EOF

    # Final validation
    if [[ -f "$OUTFILE" && -s "$OUTFILE" ]]; then
        local final_size="$(du -h "$OUTFILE" | cut -f1)"
        log_info "Report generation completed successfully"
        log_info "Report saved to: $OUTFILE"
        log_info "Generation time: ${duration} seconds"
        log_info "Final report size: $final_size"

        # Display comprehensive summary
        echo -e "\n${GREEN}========================================${NC}"
        echo -e "${GREEN}    SAP HANA REPORT GENERATED${NC}"
        echo -e "${GREEN}========================================${NC}"
        echo "[+] Report Location: $OUTFILE"
        echo "[*] Report Size: $final_size"
        echo "[T] Generation Time: ${duration} seconds"
        echo "[H] System: $(hostname -s)"
        echo "[D] Generated: $(date)"
        echo "[U] Generated by: $(whoami)"

        if [[ ${#failed_sections[@]} -gt 0 ]]; then
            echo -e "${YELLOW}[!] Sections with issues: ${#failed_sections[@]}${NC}"
        else
            echo -e "${GREEN}[OK] All sections completed successfully${NC}"
        fi

        echo -e "${GREEN}========================================${NC}"

        # Provide next steps
        echo -e "\n${BLUE}Next Steps:${NC}"
        echo "  - Review the report: cat \"$OUTFILE\""
        echo "  - Copy to another location if needed"
        echo "  - Share with SAP support if required"

    else
        log_error "Report generation failed - output file is missing or empty"
        exit 1
    fi
}

# Usage function
show_usage() {
    cat << EOF
SAP HANA System Report Generator v2.0

Usage: $0 [OPTIONS]

Options:
  -h, --help     Show this help message
  -d, --debug    Enable debug logging
  -t, --test     Run in test mode (no root required)
  -o, --output   Specify output directory (default: /root)
  -v, --verbose  Verbose output

Environment Variables:
  REPORT_DIR     Output directory for reports
  LOG_LEVEL      Logging level (DEBUG, INFO, WARN, ERROR)

Examples:
  $0                    # Standard run (requires root)
  $0 -d                 # Debug mode
  $0 -t                 # Test mode (no root check)
  $0 -o /tmp            # Custom output directory

EOF
}

# Parse command line arguments
parse_arguments() {
    while [[ $# -gt 0 ]]; do
        case $1 in
            -h|--help)
                show_usage
                exit 0
                ;;
            -d|--debug)
                LOG_LEVEL="DEBUG"
                shift
                ;;
            -t|--test)
                TEST_MODE=true
                shift
                ;;
            -o|--output)
                REPORT_DIR="$2"
                shift 2
                ;;
            -v|--verbose)
                LOG_LEVEL="DEBUG"
                shift
                ;;
            *)
                echo "Unknown option: $1" >&2
                show_usage >&2
                exit 1
                ;;
        esac
    done
}

# Script execution
parse_arguments "$@"
main