---

- name: Get Server Power Status
  uri:
    url: "https://{{ server_hardware_ilo_ip }}/redfish/v1/Chassis?$expand=."
    method: GET
    return_content: yes
    body: ""
    body_format: json
    validate_certs: no
    user: "{{ server_hardware_username }}"
    password: "{{ server_hardware_password }}"
    force_basic_auth: yes
    status_code: 200
  delegate_to: localhost
  register: status

- set_fact:
    myvar: "{{ status.json.Members[0].PowerState }}"

- debug:
    msg: "Server Power State is: {{ myvar }}"

- name: Powered ON
  uri:
    url: "https://{{ server_hardware_ilo_ip }}/redfish/v1/Systems/1/Actions/ComputerSystem.Reset"
    method: POST
    return_content: yes
    body: "{\"ResetType\": \"On\"}"
    body_format: json
    validate_certs: no
    user: "{{ server_hardware_username }}"
    password: "{{ server_hardware_password }}"
    force_basic_auth: yes
    status_code: 200
  delegate_to: localhost
  when: myvar == "Off"
  register: power

- debug:
    var=power.json.error
  when: myvar == "Off"

- name: Proliant Server Boot State
  uri:
    url: "https://{{ server_hardware_ilo_ip }}/redfish/v1/systems/1"
    method: GET
    return_content: yes
    body: ""
    body_format: json
    validate_certs: no
    user: "{{ server_hardware_username }}"
    password: "{{ server_hardware_password }}"
    force_basic_auth: yes
    status_code: 200
  delegate_to: localhost
  register: server_state
  until: server_state.status == 200 and server_state.json.Oem.Hpe.PostState == "InPostDiscoveryComplete"
  retries: 60  # Maximum number of retries
  delay: 10  # Delay between retries (seconds)

- debug:
    msg: "Proliant Server Booted Successfully..."
