---
- name: ILO REST Persistent Memory Config For GEN10 & GEN10+ Servers
  uri:
      url: "https://{{ server_hardware_ilo_ip }}/redfish/v1/Systems/1/bios/settings/"
      method: POST
      return_content: yes
      body: "{\"Attributes\": {\"MemoryControllerInterleaving\": \"Auto\",\"MaxMemBusFreqMHz\": \"Auto\" , \"MemPatrolScrubbing\": \"Enabled\", \"MemoryRemap\": \"NoAction\", \"PersistentMemAddressRangeScrub\": \"Enabled\", \"PersistentMemoryInterleaving\": \"Enabled\", \"SecurityFreezeLock\": \"Disabled\", \"ApplyDefaultNamespaces\": \"Disabled\" }}"
      body_format: json
      validate_certs: no
      user: "{{ server_hardware_username }}"
      password: "{{ server_hardware_password }}"
      force_basic_auth: yes
      status_code: 200
  when: hw_generation is search('Gen10')
  delegate_to: localhost

- name: ILO REST Persistent Memory Config For GEN11 Servers
  uri:
      url: "https://{{ server_hardware_ilo_ip }}/redfish/v1/Systems/1/bios/settings/"
      method: POST
      return_content: yes
      body: "{\"Attributes\": {\"Numa\": \"Enabled\", \"MaxMemBusFreqMHz\": \"Auto\", \"MemPatrolScrubbing\": \"Enabled\", \"MemoryRemap\": \"NoAction\", \"PersistentMemAddressRangeScrub\": \"Enabled\" }}"
      body_format: json
      validate_certs: no
      user: "{{ server_hardware_username }}"
      password: "{{ server_hardware_password }}"
      force_basic_auth: yes
      status_code: 200
  when: hw_generation is search('Gen11')
  delegate_to: localhost


- name: ILO REST POST Rebbot Server
  uri:
    url: "https://{{ server_hardware_ilo_ip }}/redfish/v1/Systems/1/Actions/ComputerSystem.Reset"
    method: POST
    return_content: yes
    body: "{\"ResetType\": \"ForceRestart\"}"
    body_format: json
    validate_certs: no
    user: "{{ server_hardware_username }}"
    password: "{{ server_hardware_password }}"
    force_basic_auth: yes
    status_code: 200
  delegate_to: localhost

- name: Proliant Server Boot State
  uri:
    url: "https://{{ server_hardware_ilo_ip }}/redfish/v1/systems/1"
    method: GET
    return_content: yes
    body: ""
    body_format: json
    validate_certs: no
    user: "{{ server_hardware_username }}"
    password: "{{ server_hardware_password }}"
    force_basic_auth: yes
    status_code: 200
  delegate_to: localhost
  register: server_state
  until: server_state.status == 200 and server_state.json.Oem.Hpe.PostState == "InPostDiscoveryComplete"
  retries: 60  # Maximum number of retries
  delay: 10  # Delay between retries (seconds)

- debug:
    msg: "Proliant Server Booted Successfully..."
