---

- name: ILO REST POST Mount Firmware ISO
  uri:
    url: "https://{{ server_hardware_ilo_ip }}/redfish/v1/Managers/1/VirtualMedia/2/Actions/VirtualMedia.InsertMedia"
    method: POST
    return_content: yes
    body: "{\"Image\": \"http://{{ gateway_host_ip }}/media/{{ installation_media }}\",\"WriteProtected\": \"true\", \"Inserted\": \"true\" }"
    body_format: json
    validate_certs: no
    user: "{{ server_hardware_username }}"
    password: "{{ server_hardware_password }}"
    force_basic_auth: yes
    status_code: 200
  delegate_to: localhost

- name: ILO REST Boot Order From ISO
  uri:
    url: "https://{{ server_hardware_ilo_ip }}/redfish/v1/Systems/1"
    method: PATCH
    return_content: yes
    body: "{\"Boot\": {\"BootSourceOverrideTarget\": \"Cd\", \"BootSourceOverrideEnabled\": \"Once\" }}"
    body_format: json
    validate_certs: no
    user: "{{ server_hardware_username }}"
    password: "{{ server_hardware_password }}"
    force_basic_auth: yes
    status_code: 200
  delegate_to: localhost

- name: Get Server Power Status
  uri:
    url: "https://{{ server_hardware_ilo_ip }}/redfish/v1/Chassis?$expand=."
    method: GET
    return_content: yes
    body: ""
    body_format: json
    validate_certs: no
    user: "{{ server_hardware_username }}"
    password: "{{ server_hardware_password }}"
    force_basic_auth: yes
    status_code: 200
  delegate_to: localhost
  register: status

- set_fact:
    myvar: "{{ status.json.Members[0].PowerState }}"

- debug:
    msg: "Server Power State is: {{ myvar }}"

- name: Server Reset If Server Powered On
  uri:
    url: "https://{{ server_hardware_ilo_ip }}/redfish/v1/Systems/1/Actions/ComputerSystem.Reset"
    method: POST
    return_content: yes
    body: "{\"ResetType\": \"ForceRestart\"}"
    body_format: json
    validate_certs: no
    user: "{{ server_hardware_username }}"
    password: "{{ server_hardware_password }}"
    force_basic_auth: yes
    status_code: 200
  delegate_to: localhost
  when: myvar == "On"
  register: power

- debug:
    var=power.json.error
  when: myvar == "On"
   
- name: Server Power On If Server Powered Off
  uri:
    url: "https://{{ server_hardware_ilo_ip }}/redfish/v1/Systems/1/Actions/ComputerSystem.Reset"
    method: POST
    return_content: yes
    body: "{\"ResetType\": \"On\"}"
    body_format: json
    validate_certs: no
    user: "{{ server_hardware_username }}"
    password: "{{ server_hardware_password }}"
    force_basic_auth: yes
    status_code: 200
  delegate_to: localhost
  when: myvar == "Off"
  register: power

- debug:
    var=power.json.error
  when: myvar == "Off"

- name: Proliant Server Boot State
  uri:
    url: "https://{{ server_hardware_ilo_ip }}/redfish/v1/systems/1"
    method: GET
    return_content: yes
    body: ""
    body_format: json
    validate_certs: no
    user: "{{ server_hardware_username }}"
    password: "{{ server_hardware_password }}"
    force_basic_auth: yes
    status_code: 200
  delegate_to: localhost
  register: server_state
  until: server_state.status == 200 and server_state.json.Oem.Hpe.PostState == "InPostDiscoveryComplete"
  retries: 60  # Maximum number of retries
  delay: 10  # Delay between retries (seconds)

- debug:
    msg: "Proliant Server Booted Successfully..."
