---
# tasks file for suse-os-preconfigure

  - name: Gathering facts
    setup:
    tags:
      - role::sap-hana-preconfigure-shared
      - role::sap-hana-preconfigure-shared::setup

  - import_tasks: 01-configure-hostname.yml
    tags:
      - role::sap-hana-preconfigure-shared
      - role::sap-hana-preconfigure-shared::hostname

  - import_tasks: 02-configure-issue.yml
    tags:
      - role::sap-hana-preconfigure-shared
      - role::sap-hana-preconfigure-shared::issue

  - import_tasks: 03-configure-network-time-and-date.yml
    tags:
    - role::sap-hana-preconfigure-shared
    - role::sap-hana-preconfigure-shared::date-time

  -  import_tasks:  04-disable-firewalld-and-selinux.yml
     tags:
     - role::sap-hana-preconfigure-shared
     - role::sap-hana-preconfigure-shared::disable-firewalld-and-selinux

  - import_tasks: 05-register-rhel.yml
    tags:
    - role::sap-hana-preconfigure-shared
    - role::sap-hana-preconfigure-shared::register-rhel

  - import_tasks: 06-required-packages.yml
    tags:
    - role::sap-hana-preconfigure-shared
    - role::sap-hana-preconfigure-shared::required-packages

  - import_tasks: 07-update-operating-system.yml
    tags:
    - role::sap-hana-preconfigure-shared
    - role::sap-hana-preconfigure-shared::update-operating-system

  - import_tasks: 08-sap-hana-filesystem.yml
    tags:
    - role::sap-hana-preconfigure-shared
    - role::sap-hana-preconfigure-shared::sap-hana-filesystem

  - import_tasks: 09-configuring-system-parameters.yml
    tags:
    - role::sap-hana-preconfigure-shared
    - role::sap-hana-preconfigure-shared::configuring-system-parameters

  - import_tasks: 10-pmem-config.yml
    when:  pmem == true
    tags:
    - role::sap-hana-preconfigure-shared
    - role::sap-hana-preconfigure-shared::pmem-config
