---

    - name: Query a file on a datastore
      vsphere_file:
        host: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ datacenter }}"
        datastore: "{{ iso_datastore }}"
        path: "{{ datastore_iso_directory }}/{{  installation_media }}"
        validate_certs: no
        state: file
      run_once: True
      delegate_to: localhost
      ignore_errors: yes
      register: iso_status

    - name: Create a directory on a datastore
      vsphere_file:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter }}"
        datastore: "{{ iso_datastore }}"
        path: "{{ datastore_iso_directory }}"
        state: directory
      run_once: True
      delegate_to: localhost
      when: iso_status.state == "absent"

    - name: Copy RHEL Installation Media to the Datastore
      vsphere_copy:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        src: "{{ hana_deployment.source }}/{{ installation_media }}"
        datacenter: "{{ datacenter }}"
        datastore: "{{ iso_datastore }}"
        path: "{{ datastore_iso_directory }}/{{ installation_media }}"
      run_once: True
      delegate_to: localhost
      when: iso_status.state == "absent"

