---
# tasks file for 01-authenticate-oneview

      - name: Authenticate Oneview User
        uri:
          url: "https://{{ oneview_ip }}/rest/login-sessions"
          method: POST
          return_content: yes
          body: "{\"password\": \"{{ oneview_password }}\", \"userName\": \"{{ oneview_username }}\", \"authLoginDomain\": \"local\" }"
          body_format: json
          validate_certs: no
          status_code: 200
        register: oneview_auth
        delegate_to: localhost

      - name: Debug
        debug:
          msg: "Oneview Session ID: {{ oneview_auth.json.sessionID }}"
