---
# tasks file for 02-time-config

     - name: Configure time locale information
       uri:
          url: "https://{{ oneview_ip }}/rest/appliance/configuration/time-locale"
          headers:
            Auth: "{{ oneview_auth.json.sessionID }}"
            X-Api-Version: 2200
            Content-Type: application/json
          method: POST
          return_content: yes
          body: "{ \"locale\": \"en_US.UTF-8\" , \"timezone\": \"UTC+0300\", \"ntpServers\": [\"{{ ntp_servers.hostname }}\"] }"
          body_format: json
          validate_certs: no
          status_code: 202
       register: configure_time
       delegate_to: localhost

  
