---
# tasks file for 04-add-server-hardware

      - name: Oneview REST Add Server Hardware
        uri:
          url: "https://{{ oneview_ip }}/rest/server-hardware"
          headers:
            Auth: "{{ oneview_auth.json.sessionID }}"
          method: POST
          return_content: yes
          body: "{\"hostname\": \"{{ server_hardware_ilo_ip }}\", \"username\": \"{{ server_hardware_username }}\", \"password\": \"{{ server_hardware_password }}\", \"force\": \"false\", \"licensingIntent\": \"OneView\", \"configurationState\": \"Monitored\" }"
          body_format: json
          validate_certs: no
          status_code: 202
        register: add_server_hw
        delegate_to: localhost

      - name: Oneview REST Add Server Task Status
        uri:
          url: "{{ add_server_hw.location }}"
          headers:
            Auth: "{{ oneview_auth.json.sessionID }}"
          method: get
          body: ""
          body_format: json
          validate_certs: no
          status_code: 200
        register: add_server_hw_result
        until: add_server_hw_result.json.percentComplete == 100
        retries: 240
        delay: 4
        delegate_to: localhost


      - name: Add Scope resources
        uri:
          url: "https://{{ oneview_ip }}/rest/scopes/resources/{{ add_server_hw_result.json.associatedResource.resourceUri }}"
          headers:
            Auth: "{{ oneview_auth.json.sessionID }}"
            X-Api-Version: 2200
            If-Match: "*"
          method: PUT
          return_content: yes
          body: "{\"resourceUri\": \"{{ add_server_hw_result.json.associatedResource.resourceUri }}\", \"scopeUris\": [\"{{ scope_uri }}\"] }"
          body_format: json
          validate_certs: no
          status_code: 202
        register: add_scope_resource
        delegate_to: localhost
