---

      - name: Get Server Hardware Status
        uri:
          url: "https://{{ oneview_ip }}/rest/server-hardware?start=0&count=-1"
          headers:
            Auth: "{{ oneview_auth.json.sessionID }}"
          method: GET
          return_content: yes
          body: ""
          body_format: json
          validate_certs: no
          status_code: 200
        register: get_server_hw
        delegate_to: localhost

      - name: List Of Hardware Info
        debug: msg="{{ get_server_hw.json.members | json_query(jmesquery) }}"
        vars:
                jmesquery: "[*].{ HW_Name: name, HW_Model: shortModel, HW_ILO_IP: mpIpAddress, HW_Serial_Number: serialNumber, HW_Part_Number: partNumber, HW_Processor_Type: processorType, HW_Processor_Count: processorCount, HW_Memory_MB: memoryMb, HW_Power_State: powerState, ILO_FW_Version: mpFirmwareVersion, HW_Bios_FW_Version: romVersion }"
