---

  - name: Ansible SAP Hana DB Directory exists.
    stat:
      path: "/usr/sap/{{ sid }}"
    register: sap_hana_directory

  - name: Creates a configuration file
    template:
      src: "hana.j2"
      dest: "/{{ hana_deployment['destination'] }}/SAP_HANA_DATABASE/hana.cfg"
      owner: root
      group: root
      mode: 0644
    when: sap_hana_directory.stat.isdir is not defined

  - name: Hana DB installation
    command:
      cmd: "./hdblcm -b --configfile=hana.cfg"
      chdir: "/{{ hana_deployment['destination'] }}/SAP_HANA_DATABASE"
    register: hana_db
    when: sap_hana_directory.stat.isdir is not defined

  - name:
    debug:
      var: hana_db.stdout_lines
      #verbosity: 2
    when: sap_hana_directory.stat.isdir is not defined
