---

  - name: Sleep for 300 seconds and continue with play
    wait_for:
      timeout: 300
    delegate_to: localhost

  - name: Enable SD-Flex 280 Virtual Media Service
    uri:
      url: "https://{{ server_hardware_rmc_ip }}/redfish/v1/Systems/{{ pnum }}"
      method: PATCH
      return_content: yes
      body: "{\"VirtualMediaConfig\": {\"ServiceEnabled\": true}}"
      body_format: json
      validate_certs: no
      user: "{{ server_hardware_username }}"
      password: "{{ server_hardware_password }}"
      force_basic_auth: yes
      status_code: 200
    when: hw_model is not search('Scale-up')
    delegate_to: localhost

  - name: Connect SD-Flex 280 Virtual Media
    uri:
      url: "https://{{ server_hardware_rmc_ip }}/redfish/v1/Systems/{{ pnum }}/VirtualMedia/CD0/Actions/VirtualMedia.InsertMedia"
      method: POST
      return_content: yes
      body: "{\"TransferProtocolType\": \"NFS\", \"Image\": \"nfs://{{ gateway_host_ip }}/home/hpe/ansible/ansible-sap-hana-deploy-sles/setup/html/media/{{ installation_media }}\"}"
      body_format: json
      validate_certs: no
      user: "{{ server_hardware_username }}"
      password: "{{ server_hardware_password }}"
      force_basic_auth: yes
      status_code: 202
    when: hw_model is not search('Scale-up')
    delegate_to: localhost

  - name: Connect Scale-Up 3200 Virtual Media
    uri:
      url: "https://{{ server_hardware_rmc_ip }}/redfish/v1/Systems/Partition{{ pnum }}/VirtualMedia/0/Actions/VirtualMedia.InsertMedia"
      method: POST
      return_content: yes
      body: "{\"TransferProtocolType\": \"NFS\", \"Image\": \"nfs://{{ gateway_host_ip }}/home/hpe/ansible/ansible-sap-hana-deploy-sles/setup/html/media/{{ installation_media }}\"}"
      body_format: json
      validate_certs: no
      user: "{{ server_hardware_username }}"
      password: "{{ server_hardware_password }}"
      force_basic_auth: yes
      status_code: 204
    when: hw_model is search('Scale-up')
    delegate_to: localhost


  - name: Reboot Sd-Flex 280 Server
    uri:
      url: "https://{{ server_hardware_rmc_ip }}/redfish/v1/Systems/{{ pnum }}/Actions/ComputerSystem.Reset"
      method: POST
      return_content: yes
      body: "{\"ResetType\": \"ForceRestart\"}"
      body_format: json
      validate_certs: no
      user: "{{ server_hardware_username }}"
      password: "{{ server_hardware_password }}"
      force_basic_auth: yes
      status_code: 200
    when: hw_model is not search('Scale-up')
    delegate_to: localhost

  - name: Reboot Scale-Up 3200 Server
    uri:
      url: "https://{{ server_hardware_rmc_ip }}/redfish/v1/Systems/Partition{{ pnum }}/Actions/ComputerSystem.Reset"
      method: POST
      return_content: yes
      body: "{\"ResetType\": \"ForceRestart\"}"
      body_format: json
      validate_certs: no
      user: "{{ server_hardware_username }}"
      password: "{{ server_hardware_password }}"
      force_basic_auth: yes
      status_code: 202
    when: hw_model is search('Scale-up')
    delegate_to: localhost

