---

- name: Tune Operating System Snapshot Parameters
  shell: |
       snapper  -c root set-config "NUMBER_LIMIT=2-10"
       snapper  -c root set-config "NUMBER_LIMIT_IMPORTANT=4-10"
       snapper  -c root set-config "NUMBER_MIN_AGE=0"
       snapper  -c root set-config "TIMELINE_CREATE=no"
       snapper  -c root set-config "TIMELINE_LIMIT_MONTHLY=0"
       snapper  -c root set-config "TIMELINE_LIMIT_YEARLY=0"


- name: Check Current Snapshot Parameters
  command: "snapper get-config"
  register: snap_conf_result

- name: Show Current Snapshot parameters
  debug:
    var: snap_conf_result.stdout_lines
