---
- name: Get Superdome Product
  uri:
    url: "https://{{ server_hardware_rmc_ip }}/redfish/v1"
    method: GET
    return_content: yes
    body: ""
    body_format: json
    validate_certs: no
    user: "{{ server_hardware_username }}"
    password: "{{ server_hardware_password }}"
    force_basic_auth: yes
    status_code: 200
  delegate_to: localhost
  register: hw_model

- set_fact:
    hw_model: "{{ hw_model.json.Product }}"

- name: Superdome Product Is
  debug:
    msg: "Superdome Product Model: {{ hw_model }}"
