---

- name: Get  Power Status
  uri:
    url: "https://{{ server_hardware_rmc_ip }}/redfish/v1/Systems/{{ pnum }}"
    method: GET
    return_content: yes
    body: ""
    body_format: json
    validate_certs: no
    user: "{{ server_hardware_username }}"
    password: "{{ server_hardware_password }}"
    force_basic_auth: yes
    status_code: 200
  delegate_to: localhost
  register: partition_state

- set_fact:
    partition_power_state: "{{ partition_state.json.PowerState }}"

- debug:
    msg: "Server Power State is: {{ partition_power_state }}"

- name: Powered ON Server
  uri:
    url: "https://{{ server_hardware_rmc_ip }}/redfish/v1/Systems/{{ pnum }}/Actions/ComputerSystem.Reset"
    method: POST
    return_content: yes
    body: "{\"ResetType\": \"On\"}"
    body_format: json
    validate_certs: no
    user: "{{ server_hardware_username }}"
    password: "{{ server_hardware_password }}"
    force_basic_auth: yes
    status_code: 202
  delegate_to: localhost
  when:
    - partition_power_state  == "Off"
  register: power

- debug:
    var=power.json.error
  when: partition_power_state == "Off"

- name: Sleep for 300 seconds and continue with play
  wait_for:
    timeout: 300
  when: partition_power_state == "Off"
  delegate_to: localhost
