---
- name: Sleep for 300 seconds and continue with play
  wait_for:
    timeout: 300
  delegate_to: localhost

- name: ILO REST Persistent Memory Config For SD-FLEX Servers
  uri:
      url: "https://{{ server_hardware_rmc_ip }}/redfish/v1/Systems/{{ pnum }}/Bios/Settings/"
      method: PATCH
      return_content: yes
      body: "{\"Attributes\": {\"Numa\": \"Enabled\", \"MaxMemBusFreqMHz\": \"Auto\", \"MemPatrolScrubbing\": \"Enabled\", \"MemoryRemap\": \"NoAction\", \"PersistentMemAddressRangeScrub\": \"Enabled\" }}"
      body_format: json
      validate_certs: no
      user: "{{ server_hardware_username }}"
      password: "{{ server_hardware_password }}"
      force_basic_auth: yes
      status_code: 200
  when: hw_model is not search('Scale-up')
  delegate_to: localhost


- name: Rebbot Server
  uri:
    url: "https://{{ server_hardware_rmc_ip }}/redfish/v1/Systems/{{ pnum }}/Actions/ComputerSystem.Reset"
    method: POST
    return_content: yes
    body: "{\"ResetType\": \"ForceRestart\"}"
    body_format: json
    validate_certs: no
    user: "{{ server_hardware_username }}"
    password: "{{ server_hardware_password }}"
    force_basic_auth: yes
    status_code: 202
  delegate_to: localhost
