---

   - name: OpenSSH client security settings
     replace:
       dest=/etc/ssh/sshd_config
       regexp="{{ item.pname }}"
       replace="{{ item.value }}"
     with_items:
       - { pname: '^PermitRootLogin\syes', value: 'PermitRootLogin no'}
       - { pname: '(?i)^#?PermitEmptyPasswords.*', value: 'PermitEmptyPasswords no'}
       - { pname: '(?i)^#?IgnoreRhosts.*', value: 'IgnoreRhosts yes'}
       - { pname: '(?i)^X11Forwarding.*', value: 'X11Forwarding no'}
       - { pname: '(?i)^#?AllowTcpForwarding.*', value: 'AllowTcpForwarding no'}
       - { pname: '(?i)^#?MaxAuthTries.*', value: 'MaxAuthTries 4'}
       - { pname: '(?i)^#?MaxSessions.*', value: 'MaxSessions 8'}
       - { pname: '(?i)^#?PrintLastLog.*', value: 'PrintLastLog yes'}
       - { pname: '(?i)^#?PermitUserEnvironment.*', value: 'PermitUserEnvironment no'}
       - { pname: '(?i)^#?LoginGraceTime.*', value: 'LoginGraceTime 60'}
       - { pname: '(?i)^#?Compression.*', value: 'Compression no'}
       - { pname: '(?i)^#?StrictModes.*', value: 'StrictModes yes'}

   - name: Assign SSH Allowed Users
     lineinfile:
       path: /etc/ssh/sshd_config
       line: "{{ item }}"
     with_items:
       - 'AllowUsers oper'
       - 'maxstartups 10:30:60'

   - name: Use Only Strong Ciphers And Mac Hashes
     blockinfile:
       path: /etc/ssh/sshd_config
       marker: "## {mark} added by ansible (Strong Ciphers And Mac Hashes Parameters)"
       content: |
                #
                # Use Storange Ciphers
                Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
                # Use Strong MAC Hashes
                MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256
                #Use Strong Kex Algorthims
                KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256
