---

   - name: Restrict sudo for normal users
     replace:
       dest=/etc/sudoers
       regexp="{{ item.pname }}"
       replace="{{ item.value }}"
     with_items:
       - { pname: '^ALL\s+ALL=\(ALL\)\s+ALL', value: '#ALL ALL=(ALL) ALL # WARNING! Only use this together with Defaults targetpw !'}
       - { pname: '^#\s+%wheel\s+ALL=\(ALL:ALL\)\s+ALL', value: '%wheel ALL=(ALL) ALL'}
       - { pname: '^Defaults\s+targetpw', value: 'Defaults !targetpw'}

   - name: Ensure invoking users password for privilege escalation when using sudo
     lineinfile:
       dest: /etc/sudoers
       insertafter: '^Defaults\s+!targetpw'
       line: "{{ item }}"
     with_items:
       - 'Defaults !rootpw'
       - 'Defaults !runaspw'
       - 'Defaults timestamp_timeout=3'
 
