---

   - name: Modify login definitions according to corporate security policies
     replace:
       dest=/etc/login.defs
       regexp="{{ item.pname }}"
       replace="{{ item.value }}"
     with_items:
       - { pname: '^PASS_MAX_DAYS(\s+.*)?$', value: 'PASS_MAX_DAYS 270'}
       - { pname: '^PASS_MIN_DAYS(\s+.*)?$', value: 'PASS_MIN_DAYS 7'}
       - { pname: '^PASS_WARN_AGE(\s+.*)?$', value: 'PASS_WARN_AGE 30'}

   - name: Set default inactive time to 45 Min
     blockinfile:
       path: /etc/profile.d/timeout.sh
       create: yes
       marker: "## {mark} added by ansible (Add Timeout Parameter)"
       content: |
                #
                # Timeout in seconds till the bash session is terminated
                # in case of inactivity.
                # 45min = 2700 sec
                TMOUT=2700
                readonly TMOUT
                export TMOUT

   - name: Ensure that /etc/pam.d/login contains the pam_securetty module in the auth block
     pamd:
       name: login
       type: auth
       control: requisite
       module_path: pam_nologin.so
       new_type: auth
       new_control: '[user_unknown=ignore success=ok ignore=ignore auth_err=die default=bad]'
       new_module_path: pam_securetty.so
       state: after

   - name: Comment Out or Remove all tty's in the file /etc/securetty except of tty1
     lineinfile:
       path: /etc/securetty
       regexp: '^tty[2-6]'
       state: absent

   - name: Limit the Number of Concurrent Login Sessions Allowed for whell group
     pam_limits:
       domain: "@wheel"
       limit_type: hard
       limit_item: maxlogins
       value: "10"
