---

   - name: Setup password strengthening for user accounts
     command: pam-config --add --cracklib-retry=3 --cracklib-minlen=8 --cracklib-lcredit=-1 --cracklib-ucredit=-1 --cracklib-dcredit=-1 --cracklib-ocredit=0 --cracklib-difok=5 

   - name: Set PAM''s Password Hashing Algorithm
     command: pam-config --add --unix-sha512

