---

   - name: Modify permissions on certain system files
     replace:
       dest=/etc/sysconfig/security
       regexp="^PERMISSION_SECURITY=(.*)?$"
       replace='PERMISSION_SECURITY="easy local"'
     notify: chkstat

   - name: Force security services
     meta: flush_handlers

   - name: following permission settings to the file /etc/permissions.local
     blockinfile:
       path: /etc/permissions.local
       create: yes
       marker: "# {mark} HANA Security Hardening"
       content: |
                 /etc/at.allow root:root 0400
                 /etc/bash.bashrc root:root 0444
                 /etc/csh.cshrc root:root 0444
                 /etc/csh.login root:root 0444
                 /etc/shadow root:shadow 0440
                 /etc/rsyslog.conf root:root 0400
                 /etc/crontab root:root 0400
                 /etc/cron.d root:root 0700
                 /etc/cron.hourly root:root 0700
                 /etc/cron.daily root:root 0700
                 /etc/cron.weekly root:root 0700
                 /etc/cron.monthly root:root 0700
                 /etc/login.defs root:root 0400
                 /etc/security/access.conf root:root 0400
                 /etc/sysctl.conf root:root 0400
                 /etc/X11/xdm/Xservers root:root 0444
                 /root root:root 0700
                 /root/.cshrc root:root 0400
                 /var/log/boot.log root:root 0640
                 /var/log/sa root:root 0770
                 #
                 # Changing permissions of utmp files would cause the commands
                 # w, who and last not to work anymore for non-root users
                 #
                 # Uncomment these lines, if you are really sure about that
                 #           /var/run/utmp root:utmp 0600
                 #           /var/log/wtmp root:utmp 0600
     notify: chkstat

   - name: Force security services
     meta: flush_handlers
