---
# tasks file for suse-os-preconfigure

  - name: Gathering facts
    setup:
    tags:
      - role::sap-hana-preconfigure-vmware
      - role::sap-hana-preconfigure-vmware::setup

  - import_tasks: 01-configure-hostname.yml
    tags:
      - role::sap-hana-preconfigure-vmware
      - role::sap-hana-preconfigure-vmware::hostname

  - import_tasks: 02-configure-issue.yml
    tags:
      - role::sap-hana-preconfigure-vmware
      - role::sap-hana-preconfigure-vmware::issue

  - import_tasks: 03-configure-network-time-and-date.yml
    tags:
      - role::sap-hana-preconfigure-vmware
      - role::sap-hana-preconfigure-vmware::date-time

  -  import_tasks: 04-tune-snapshot-parameters.yml
     tags:
     - role::sap-hana-preconfigure-vmware
     - role::sap-hana-preconfigure-vmware::snapshot

  - import_tasks: 05-register-suse.yml
    tags:
    - role::sap-hana-preconfigure-vmware
    - role::sap-hana-preconfigure-vmware::register-suse

  - import_tasks: 06-update-operating-system.yml
    tags:
    - role::sap-hana-preconfigure-vmware
    - role::sap-hana-preconfigure-vmware::update-os

  - import_tasks: 07-sap-hana-filesystem.yml
    tags:
    - role::sap-hana-preconfigure-vmware
    - role::sap-hana-preconfigure-vmware::filesystem

  - import_tasks: 08-configuring-system-parameters.yml
    tags:
    - role::sap-hana-preconfigure-vmware
    - role::sap-hana-preconfigure-vmware::system-parameters

  - import_tasks: 09-pmem-config.yml
    when:  pmem == true
    tags:
    - role::sap-hana-preconfigure-vmware
    - role::sap-hana-preconfigure-vmware::pmem-config
